spring:
  application:
    name: esword-cli
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:sqlite:kjv+matches.bbli
    driverClassName: org.sqlite.JDBC
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  sql:
    init:
      mode: always
logging:
  level:
    root: ERROR
    com:
      codified: DEBUG